### PR TITLE
Add tests for missing methods

### PR DESCRIPTION
**Pull request by yanagibashi**
open-mpi/ompi#3402 added missing Java binding methods to Open MPI.
These test programs correspond to those methods.

Signed-off-by: Tsubasa Yanagibashi <fj2505dt@aa.jp.fujitsu.com>

### CODE REVIEW

**Comment by kawashima-fj** [comment]
@nrgraham23, @yanagibashi is my colleague. Could you check and pull this?

@hppritcha, You asked me on the F2F OMPI dev meeting last month which Java version Fujitsu use for post-K computer. We plan to use upcoming Java 9.

**Comment by nrgraham23** [comment]
Sorry I haven't gotten to this yet.  Ill give it a look after work tonight.

**Comment by nrgraham23** [comment]
I looked through the code and it all looks good to me.  I don't have a setup to test it though.

@hppritcha could you give this a try and merge it if you are satisfied?

**Comment by kawashima-fj** [comment]
@hppritcha Is this OK? I don't have a permission to pull it to `ompi-java-tests` repository.

**Comment by hppritcha** [comment]
@kawashima-fj you should be able to merge now.  Thanks for the new tests!

**Pull request merged**
